apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: envious-raccoon-go-gitops
  description: This is GitOps manifest for envious-raccoon-go   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-name: envious-raccoon-go
    janus-idp.io/tekton: envious-raccoon-go 
    backstage.io/kubernetes-id: envious-raccoon-go 
    backstage.io/techdocs-ref: dir:. 
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:envious-raccoon-go
