apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: envious-raccoon-go
  janus-idp.io/tekton: envious-raccoon-go
  backstage.io/kubernetes-id: envious-raccoon-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: envious-raccoon-go
resources:
- deployment.yaml
- route.yaml
- service.yaml
